# Generated by Django 5.2.6 on 2025-09-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('characteristics', models.JSONField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
